# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RongYun' do

pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/RedPacket'
pod 'RongCloudIM/CallKit'


end
